# https://projecteuler.net/problem=2
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

def sum_even_fibonacci(limit):
    a, b = 1, 2
    total = 0

    while a <= limit:
        if a % 2 == 0:
            total += a
        a, b = b, a + b

    return total

result = sum_even_fibonacci(4_000_000)
print("Sum of even Fibonacci numbers up to 4,000,000:", result)
